# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python version
      uses: actions/setup-python@v2
      with:
        python-version: 3.8


    - name: Create and start virtual environment
      run: |
          python3 -m venv venv
          source venv/bin/activate


    - name: Install dependencies
      run: pip install -r backend/requirements.txt

    - name: Check Erors
      run: python backend/manage.py check

    - name: Run tests
      run: python backend/manage.py test
